### ISSUE TITLE
Some text controls on MacOS are not high enough

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/ballpit#10]
On MacOS, the text control containing the path to the radius file as well as the text control containing the maximum tree depth input are not high enough to fit the text. This issue began with commit 7b322b5.

<img width="749" alt="Screenshot 2020-08-03 at 17 30 50" src="https://user-images.githubusercontent.com/65410083/89203272-9b9feb80-d5b4-11ea-816b-b493f3e03357.png">

**Comment by rlavendomme** [comment]
I might have a solution. While testing implementation of new panels, I noticed that the SetSizer or SetSizerAndFit functions need to be done in a specific order.
They should be done from most-grand-children panels to parent panels. 
Indeed, the original code (i) initialized parent panels with default size, (ii) initialized children panels with default size, (iii) SetSizer of parent panels based on children panels, (iv) initialized grand-children panels with default size, (v) SetSizer of children panels based on grand-children panels.
Therefore, the SetSizer function for the parent panel did not include the size of grand-children panels since they didn't exist yet in the children panels.

The code would need to be reworked to proceed in this order: (i) initialize parent panels with default size, (ii) initialize children panels with default size, (iii) initialized grand-children panels with default size, (iv) SetSizer of children panels based on grand-children panels, (v) SetSizer of parent panels based on children panels.

I haven't tested this potential solution but it would be worth trying to keep default sizes from now on.

**Comment by rlavendomme** [comment]
I tested the solution I suggested above.
I made a new function in base_init.cpp dedicated to set sizers of all panels and moved all sizer related lines inside in the good order. It seems to work.
I'll add that in a new branch at the same time as the custom radii panel implementation.
