### ISSUE TITLE
Adding a panel allowing the user to define custom radii

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/ballpit#11]
In order to meet the needs of most users, it would be useful to have a panel displaying elements found in the structure file and allowing the user to define custom radius values.
Other useful features that could be included in such a panel would be:
1) to include/exclude specific elements
2) to define radius for elements not existing in the radii definition file (such as D for deuterium, Hali/Haro for aliphatic and aromatic protons, Feio for ionic radius of Fe instead of vdw radius)
3) show the number of atoms detected for each element (+ the "molecular" formula)

Such a panel would require to have a "load structure" button to read elements and display everything on the panel, then when the user clicks on "start", the values from this panel would be read to create the atom map for the calculation.

All the parameters should be reported in the output file to keep a record of how the result was obtained.

See the attached picture for an example of such a panel.
![element radii panel](https://user-images.githubusercontent.com/65511614/89716950-b1951e00-d9b1-11ea-8cd8-759ac9fd287e.png)

**Comment by jmaglic** [comment]
Good idea.

Why not make the "Default Radius" text controls editable, and let the user overwrite them with their custom radius? Later on, when the calculation is started, the radii can be read directly from these text controls and update the radius map if any values have been changed. That way you don't need the "Use Custom" checkboxes and the "Custom Radius" text controls. I think this is a more elegant solution, since it leaves more space for necessary GUI elements.

Will the "Include" checkbox simply set the radius to 0 then? I think this is the easiest way to implement this, and you should probably go for it. But down the line we should make it so that all elements that are excluded are stored, and that those atoms will never be checked.

**Comment by rlavendomme** [comment]
For the suggestion of have a single radius column, I thought about it and it is simple to do but I considered that having the official default value displayed permanently on screen could be useful.
Having the checkbox could avoid some user mistakes where he could inadvertently click on the box and change something by trying to navigate through the grid (some structures might have many different elements and lead to scroll bars on the grid).

For the second point, setting the radius to 0 would not be sufficient:
- For vdw volume calculation, if a voxel is positioned exactly at the same coordinates, it would count as a filled voxel.
- For other volume calculations, the distance is important, so even if an atom has a radius of 0, the probe would not be able to go through it.

The way I am writing the code is to click on load file:
1) Click on "load files", send files paths to controller
2) controller sends requests to the model to read radii and structure file
3) controller sends back to the gui a vector of tuple with the elements detected, radii, number of atoms
4) guicontrol use the vector to grow and fill the grid
next is what I still have to do
5) have interactive grid with cells changing color depending on conditions
6) use radii data in grid to start calculation instead of the radii file

**Comment by jmaglic** [comment]
> For the suggestion of have a single radius column, I thought about it and it is simple to do but I considered that having the official default value displayed permanently on screen could be useful.
Having the checkbox could avoid some user mistakes where he could inadvertently click on the box and change something by trying to navigate through the grid (some structures might have many different elements and lead to scroll bars on the grid).

We could make it so that if the value has been changed the text control changes colour. That way it would be immediately clear for the user if they're using the default value or if they have changed it (accidentally or otherwise). I think it's generally sensible to assume the user is going to make mistakes, but I also think that the more text fields and checkboxes you have the larger the change for mistakes is. Also, having to check a checkbox AND type in a default value is redundant, and seems like it would slow down the work flow. A solid program needs to accommodate people who frequently use it.

**Comment by rlavendomme** [comment]
I can agree that fewer information on the gui will be less intimidating (or more user friendly).
I'll go with the change of color and removal of last two columns.

I personally like to have access to all information but the tendency seems to go in the opposite direction for nowadays softwares and OS. I suppose that most user prefer it this way even if I don't.
