### ISSUE TITLE
Manual import should not be required

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/ballpit#22]
It should be possible for the user to select the import files, then press the "calculate" button directly without manually pressing the "load" button. This requires setting a flag for when loading has been completed before, but also requires checking whether the input files have been changed.

**Comment by rlavendomme** [comment]
I understand the reasoning: limiting the number of buttons to simplify the use of the program.
Yet, there are several issues with going this way:
1) Clicking once on "Start" (the "calculate" button in the code) will read the files and create the atom list grid but not actually start the calculation. So, it would be necessary to raise a prompt for the user to actually check/modify the atom list grid and click again on the "Start" button. It is not intuitive that the Start button would have two uses. This could be fixed by renaming the button after the file loading (e.g. Loading files => Start calculation).
2) As you wrote, the code becomes more complicated since we need to raise flag so the "Start" button goes back to its first function if the input files changes. A side issue is that the user could modify the input files while the program is running and the program would not be able to detect the change (e.g. changing a radius in the radii definition file). In such a situation, the "Start" button would not go back to its load file function. I know, it's overthinking and unlikely to happen but it is a possibility and preventing foreseeable issues is better than just leaving it as it is.

Do you think that the only positive point (having a single button to simplify the user interface) is that much prevailing over the cons?

If you can make it work flawlessly while preventing foreseeable issues, go for it.

**Comment by BSVogler** [comment]
I agree with jmaglic. Keep the calculation button and rename the loading button to a "reload", possibly make it smaller/use an icon. From the perspective of macOS UI this should be hidden in a menu bar item.

**Comment by rlavendomme** [comment]
> 
> 
> I agree with jmaglic. Keep the calculation button and rename the loading button to a "reload", possibly make it smaller/use an icon. From the perspective of macOS UI this should be hidden in a menu bar item.

I might have misunderstood something there. I thought jmaglic wanted to remove completely the "load files" button. In which case, it couldn't be renamed "reload" because it wouldn't exist at all. Am I wrong?
If we keep two buttons, I see no pro in removing the original "Load files" button purpose since the complete calculation goes over three steps anyway:
1) Loading files
2) Let the user check/change parameters and atom list
3) Start the calculation

Load files and reload files are basically the same action but you want to separate them over two buttons and give the "Start" button two different uses?! (again, I might be misunderstanding something here so I apologize if it is the case)

**Comment by jmaglic** [comment]
I think you misunderstood. What I mean is that it should be possible to select the input files and then, *without pressing "Load"*, press "Start" to begin the calculation. If the user has not previously pressed the "Load" button, then - before beginning the calculation - the "Load" button is essentially pressed by the program.

The "Load" button would still need to exists. For instance, the user needs a way to import the atom table before starting the calculation. The user also may want the option to reset the atom table, after having made changes. Both of these functions could also be done by a "Reload" button.

My rationale for this change is that the typical user will not need to modify radii or exclude elements, but just wants to start the calculation as fast as possible. I think there's really no argument against this. I will upload the code for this change.

**Comment by rlavendomme** [comment]
I agree that it is good to run the calculation fast by simply clicking on one button.
The only potential issue is that the user would not see the atom list, so if our algorithm wrongly recognize atoms from lines that are not atoms, then they would be included without leaving the user a chance to check the atom list.
But I concede that this is an unlikely event.


So, to summarize, you propose that we would have a "Load file" button that transforms into "Reload files" if either the "Load file" or "Start" button is pressed.
If the "Load file" button is not pressed, the "Start" button would first "press" the "Load file" button.

In this case, I agree.
