### ISSUE TITLE
Default size of the window doesn't fit all child frames

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/ballpit#7]
When starting the program, the window appears with a default size showing only the browse panel and the parameters panel but not the send and receive panel.

After testing, there are two causes to that in base_init.cpp :
1) The SetSizer() function that is meant to resize the MainWin to the sum of heights of its child frames should be changed to SetSizerAndFit().

2) The child panels don't actually have sizes since they were created with wxDefaultSize which is equal to -1,-1. Therefore, the SetSizer function can only lead to -3 by adding all vertical heights.

I will submit fix to address this issue. If you have better ideas, feel free to reject the proposition.

**Comment by jmaglic** [comment]
I commented on your commit. Your changes break some of the UI features in my build. Do they work for you?

The reason I avoided explicitly setting sizes for the widgets is because I believe having the window and the widgets be dynamic is beneficial. It allows the user to resize the window with the widgets filling additional space.

You are right that the default size window is too small to fit all widgets and I have neglected to solve this issue because I decided to work on the back end. But at least on my end, your commit doesn't solve this? Is this due to me working on MacOS or does the issue persist for you too?

**Comment by rlavendomme** [comment]
My commit solves the issue in the sense that all widgets are visible from start. The heights that I proposed might not be well suited for text displayed on different OS.
Are you saying that some widgets are still not fully visible when you start the program despite the fix?

Of course, it would be better if everything could be visible and that default sizes matched everything but the way you coded the main window dimensions doesn't seem suited for that (addition of widgets sizes).
There might be another option to ensure that all widgets are visible. Maybe a different link (parent/child) between the main window and inside frames?
![size cavol](https://user-images.githubusercontent.com/65511614/89202928-01d83e80-d5b4-11ea-8f62-8aa36cdb7116.png)

**Comment by jmaglic** [comment]
Actually, it seems that the original issue is fixed for me as well. When I open the program the default window is large enough to contain all widgets. However, the text box issue persists. I'll mark this issue as closed and open another one so we can keep track of this.
